- base_url: http://twistedmatrix.com/trac/
  tracker_name: Twisted
  bugimporter: trac.SynchronousTracBugImporter
  documentation_text: documentation
  documentation_type: keywords
  bitesized_text: easy
  bitesized_type: keywords
